name: Build Fabric Mod

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: 17
      - name: Grant Gradle permission
        run: chmod +x ./gradlew
      - name: Build the mod
        run: ./gradlew build
      - name: Upload .jar
        uses: actions/upload-artifact@v3
        with:
          name: FabricMod
          path: build/libs/*.jar
